spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  datasource:
    url: ${db-url:jdbc:postgresql://localhost:5432/postgres} #//Your DB
    username: ${db-username:postgres}  #//Your name
    password: ${db-password:relocate} #//Your password
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
server:
  port: 8080